### ISSUE TITLE
사전학습

### ISSUE THREAD

**Issue by earthkingman** [Wanted-Free-Pre-Onboarding-Course-10/Assignment2#1]
### 제목
사전학습
### 사전 학습 내용
- [x] Nest JS
- [x] GraphQL
- [x] neo4j

**Comment by earthkingman** [comment]
박지율
- [정리본](https://github.com/Wanted-Free-Pre-Onboarding-Course-10/Assignment2/wiki/%EC%82%AC%EC%A0%84%ED%95%99%EC%8A%B5-%EB%B0%95%EC%A7%80%EC%9C%A8)
- [코드](https://github.com/Wanted-Free-Pre-Onboarding-Course-10/Assignment2/tree/feature/initProject_ji_park)
 Nest Js, GraphQL 만 학습했습니다.


참고 자료
https://wikidocs.net/50747
https://jakekwak.gitbook.io/nestjs/graphql/resolvers

**Comment by YeomJaeSeon** [comment]
염재선
   - <a href="https://github.com/Wanted-Free-Pre-Onboarding-Course-10/Assignment2/wiki/%EC%82%AC%EC%A0%84%ED%95%99%EC%8A%B5--%EC%97%BC%EC%9E%AC%EC%84%A0">정리본</a>
